version: '3.8'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: web-app1
    restart: unless-stopped
    environment:
      - DB_HOST=192.168.56.10
      - DB_USER=app1_user
      - DB_PASSWORD=password_app1
      - DB_NAME=app1_db
    ports:
      - "3000:5000"
    networks:
      - dmz_network
    user: "1000:1000"

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: web-app2
    restart: unless-stopped
    environment:
      - DB_HOST=192.168.56.10
      - DB_USER=app2_user
      - DB_PASSWORD=password_app2
      - DB_NAME=app2_db
    ports:
      - "8080:5000"
    networks:
      - dmz_network
    user: "1000:1000"

networks:
  dmz_network:
    driver: bridge